# -*- coding: utf-8 -*-
"""Exercises_ End of geometry_ilayda_sevgi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQ4Kp700gzAEGOcwrhJ3dPlaJubuLUi6

## 15. Equations of second-order curves (conic sections)

# Task 1
Find the equation of a circle with center at point
A
(
1
,
2
)
 and radius
r
=
3
.

(x−h)
2
 +(y−k)
2
 =r
2

Given:
Center:
A
(
1
,
2
)
A(1,2), so
h
=
1
h=1 and
k
=
2
k=2
Radius:
r
=
3
r=3
Substitute the values:
(
x
−
1
)
2
+
(
y
−
2
)
2
=
3
2
(x−1)
2
 +(y−2)
2
 =3
2

(
x
−
1
)
2
+
(
y
−
2
)
2
=
9
(x−1)
2
 +(y−2)
2
 =9

Final Equation:
(
x
−
1
)
2
+
(
y
−
2
)
2
=
9
(x−1)
2
 +(y−2)
2
 =9

# Task 2
Find the equation of a parabola intersecting the
O
x
 axis at points
x
=
2
,
x
=
4
, and passing through point
y
(
3
)
=
1
.

Given:
Roots (intersections with
O
x
Ox-axis):
x
1
=
2
x
1
​
 =2,
x
2
=
4
x
2
​
 =4
Point:
(
x
,
y
)
=
(
3
,
1
)
(x,y)=(3,1)
Substitute
x
1
=
2
x
1
​
 =2 and
x
2
=
4
x
2
​
 =4 into the general equation:

y
=
a
(
x
−
2
)
(
x
−
4
)
y=a(x−2)(x−4)
Now substitute
(
x
,
y
)
=
(
3
,
1
)
(x,y)=(3,1) to find
a
a:

1
=
a
(
3
−
2
)
(
3
−
4
)
1=a(3−2)(3−4)
1
=
a
(
1
)
(
−
1
)
1=a(1)(−1)
a
=
−
1
a=−1

Final Equation:
y
=
−
1
(
x
−
2
)
(
x
−
4
)
y=−1(x−2)(x−4)

Simplify:

y
=
−
(
x
2
−
6
x
+
8
)
y=−(x
2
 −6x+8)
y
=
−
x
2
+
6
x
−
8
y=−x
2
 +6x−8

Final Answer:
y
=
−
x
2
+
6
x
−
8
y=−x
2
 +6x−8

# Task 3

Find the center of the ellipse with the equation
x
2
+
4
y
2
−
4
x
−
16
y
+
16
=
0
.

Given equation:
x
2
+
4
y
2
−
4
x
−
16
y
+
16
=
0
x
2
 +4y
2
 −4x−16y+16=0
Step 1: Group
x
x- and
y
y-terms:
(
x
2
−
4
x
)
+
4
(
y
2
−
4
y
)
+
16
=
0
(x
2
 −4x)+4(y
2
 −4y)+16=0
Step 2: Complete the square for
x
x-terms:
For
x
2
−
4
x
x
2
 −4x: Take half the coefficient of
x
x, square it, and add/subtract it:
x
2
−
4
x
→
(
x
2
−
4
x
+
4
)
−
4
=
(
x
−
2
)
2
−
4
x
2
 −4x→(x
2
 −4x+4)−4=(x−2)
2
 −4
Step 3: Complete the square for
y
y-terms:
For
y
2
−
4
y
y
2
 −4y: Take half the coefficient of
y
y, square it, and add/subtract it:
y
2
−
4
y
→
(
y
2
−
4
y
+
4
)
−
4
=
(
y
−
2
)
2
−
4
y
2
 −4y→(y
2
 −4y+4)−4=(y−2)
2
 −4
Step 4: Substitute back into the equation:
(
x
−
2
)
2
−
4
+
4
(
(
y
−
2
)
2
−
4
)
+
16
=
0
(x−2)
2
 −4+4((y−2)
2
 −4)+16=0
(
x
−
2
)
2
−
4
+
4
(
y
−
2
)
2
−
16
+
16
=
0
(x−2)
2
 −4+4(y−2)
2
 −16+16=0
(
x
−
2
)
2
+
4
(
y
−
2
)
2
−
4
=
0
(x−2)
2
 +4(y−2)
2
 −4=0
(
x
−
2
)
2
+
4
(
y
−
2
)
2
=
4
(x−2)
2
 +4(y−2)
2
 =4
Step 5: Standardize:
Divide through by 4 to put the equation in standard form:

(
x
−
2
)
2
4
+
(
y
−
2
)
2
1
=
1
4
(x−2)
2

​
 +
1
(y−2)
2

​
 =1
Center of the ellipse:
From the standard form
(
x
−
h
)
2
a
2
+
(
y
−
k
)
2
b
2
=
1
a
2

(x−h)
2

​
 +
b
2

(y−k)
2

​
 =1, the center is
(
h
,
k
)
(h,k).

Here, the center is:

(
2
,
2
)
(2,2)

# Task 4
Find the slope (
m
>
0
) of the line
y
=
m
x
−
5
 that is tangent to the circle with the equation
x
2
+
y
2
=
1
.

Substitute
y
=
m
x
−
5
y=mx−5 into
x
2
+
y
2
=
1
x
2
 +y
2
 =1
Substituting
y
=
m
x
−
5
y=mx−5 into
x
2
+
y
2
=
1
x
2
 +y
2
 =1:

x
2
+
(
m
x
−
5
)
2
=
1
x
2
 +(mx−5)
2
 =1
Expand
(
m
x
−
5
)
2
(mx−5)
2
 :

x
2
+
(
m
2
x
2
−
10
m
x
+
25
)
=
1
x
2
 +(m
2
 x
2
 −10mx+25)=1
Simplify:

x
2
+
m
2
x
2
−
10
m
x
+
25
=
1
x
2
 +m
2
 x
2
 −10mx+25=1
Combine like terms:

(
1
+
m
2
)
x
2
−
10
m
x
+
24
=
0
(1+m
2
 )x
2
 −10mx+24=0
Here:

a
=
1
+
m
2
,
b
=
−
10
m
,
c
=
24
a=1+m
2
 ,b=−10m,c=24
Substitute into
Δ
Δ:

Δ
=
(
−
10
m
)
2
−
4
(
1
+
m
2
)
(
24
)
Δ=(−10m)
2
 −4(1+m
2
 )(24)
Δ
=
100
m
2
−
96
(
1
+
m
2
)
Δ=100m
2
 −96(1+m
2
 )
Δ
=
100
m
2
−
96
−
96
m
2
Δ=100m
2
 −96−96m
2

Δ
=
4
m
2
−
96
Δ=4m
2
 −96
Set
Δ
=
0
Δ=0:

4
m
2
−
96
=
0
4m
2
 −96=0
4
m
2
=
96
4m
2
 =96
m
2
=
24
m
2
 =24
m
=
24
=
2
6
(
since
m
>
0
)
m=
24
​
 =2
6
​
 (since m>0)
The slope of the line is:

m
=
2
6
m=2
6
​

# Task 5
Find the intersection points of the hyperbola
x
2
−
y
2
=
1
 with the ellipse's line
x
2
+
4
y
2
=
6
.

Eliminate
x
2
x
2

From equation (1):

x
2
=
y
2
+
1
x
2
 =y
2
 +1
Substitute
x
2
=
y
2
+
1
x
2
 =y
2
 +1 into equation (2):

(
y
2
+
1
)
+
4
y
2
=
6
(y
2
 +1)+4y
2
 =6
y
2
+
4
y
2
+
1
=
6
y
2
 +4y
2
 +1=6
5
y
2
+
1
=
6
5y
2
 +1=6
5
y
2
=
5
5y
2
 =5
y
2
=
1
y
2
 =1
Solve for
y
y
y
=
±
1
y=±1
Solve for
x
x
Substitute
y
=
±
1
y=±1 into
x
2
=
y
2
+
1
x
2
 =y
2
 +1:

x
2
=
1
+
1
=
2
x
2
 =1+1=2
x
=
±
2
x=±
2
​

Intersection Points
The intersection points are:

(
2
,
1
)
,

(
2
,
−
1
)
,

(
−
2
,
1
)
,

(
−
2
,
−
1
)
(
2
​
 ,1),(
2
​
 ,−1),(−
2
​
 ,1),(−
2
​
 ,−1)
The intersection points are:

(
2
,
1
)
,

(
2
,
−
1
)
,

(
−
2
,
1
)
,

(
−
2
,
−
1
)
(
2
​
 ,1),(
2
​
 ,−1),(−
2
​
 ,1),(−
2
​
 ,−1)

# Task 6
For the given hyperbola
x
2
−
y
2
=
1
, find the distance between its branches.

The hyperbola
x
2
−
y
2
=
1
x
2
 −y
2
 =1 is in standard form:

x
2
1
−
y
2
1
=
1
1
x
2

​
 −
1
y
2

​
 =1
Vertices:
(
±
1
,
0
)
(±1,0)
Asymptotes:
y
=
±
x
y=±x

a
2

x
2

​
 −
b
2

y
2

​
 =1,
a
2
 =1,b
2
 =1⟹b=1
Thus, the distance between the branches is:

2
b
=
2
(
1
)
=
2
2b=2(1)=2
Final Answer:
The distance between the branches of the hyperbola
x
2
−
y
2
=
1
x
2
 −y
2
 =1 is:

2
2
​

## 16. Equations of planes in space

# Task 1
The plane passes through points
A
(
1
,
2
,
3
)
,
B
(
3
,
4
,
5
)
, and
C
(
2
,
1
,
4
)
. Find the equation of the plane.

Determine two vectors on the plane
Using points
A
A,
B
B, and
C
C, compute two vectors lying on the plane:

A
B
⃗
=
B
−
A
=
(
3
−
1
,
4
−
2
,
5
−
3
)
=
(
2
,
2
,
2
)
AB
 =B−A=(3−1,4−2,5−3)=(2,2,2)
A
C
⃗
=
C
−
A
=
(
2
−
1
,
1
−
2
,
4
−
3
)
=
(
1
,
−
1
,
1
)
AC
 =C−A=(2−1,1−2,4−3)=(1,−1,1)

Compute the cross product of
A
B
⃗
AB
  and
A
C
⃗
AC

The cross product
A
B
⃗
×
A
C
⃗
AB
 ×
AC
  gives a vector normal to the plane:

A
B
⃗
×
A
C
⃗
=
∣
i
j
k
2
2
2
1
−
1
1

∣
AB
 ×
AC
 =
​
  
i
2
1
​
  
j
2
−1
​
  
k
2
1
​
  
​

Expand the determinant:

A
B
⃗
×
A
C
⃗
=
i
∣
2
2
−
1
1

∣
−
j
∣
2
2
1
1

∣
+
k
∣
2
2
1
−
1

∣
AB
 ×
AC
 =i
​
  
2
−1
​
  
2
1
​
  
​
 −j
​
  
2
1
​
  
2
1
​
  
​
 +k
​
  
2
1
​
  
2
−1
​
  
​

Compute the minors:

∣
2
2
−
1
1

∣
=
(
2
)
(
1
)
−
(
2
)
(
−
1
)
=
2
+
2
=
4
​
  
2
−1
​
  
2
1
​
  
​
 =(2)(1)−(2)(−1)=2+2=4
∣
2
2
1
1

∣
=
(
2
)
(
1
)
−
(
2
)
(
1
)
=
2
−
2
=
0
​
  
2
1
​
  
2
1
​
  
​
 =(2)(1)−(2)(1)=2−2=0
∣
2
2
1
−
1

∣
=
(
2
)
(
−
1
)
−
(
2
)
(
1
)
=
−
2
−
2
=
−
4
​
  
2
1
​
  
2
−1
​
  
​
 =(2)(−1)−(2)(1)=−2−2=−4
Thus:

A
B
⃗
×
A
C
⃗
=
4
i
−
0
j
−
4
k
AB
 ×
AC
 =4i−0j−4k
A
B
⃗
×
A
C
⃗
=
(
4
,
0
,
−
4
)
AB
 ×
AC
 =(4,0,−4)

Write the equation of the plane
The normal vector to the plane is
n
⃗
=
(
4
,
0
,
−
4
)
n
 =(4,0,−4), so the equation of the plane is:

4
x
+
0
y
−
4
z
+
d
=
0
4x+0y−4z+d=0
4
x
−
4
z
+
d
=
0
4x−4z+d=0
Substitute point
A
(
1
,
2
,
3
)
A(1,2,3) into the equation to find
d
d:

4
(
1
)
−
4
(
3
)
+
d
=
0
4(1)−4(3)+d=0
4
−
12
+
d
=
0
4−12+d=0
d
=
8
d=8
Thus, the equation of the plane is:

4
x
−
4
z
+
8
=
0
4x−4z+8=0
or simplified:

x
−
z
+
2
=
0
x−z+2=0

The equation of the plane is:

x
−
z
+
2
=
0
x−z+2=0
​

# Task 2
The plane passes through point
A
(
1
,
2
,
3
)
 and is parallel to the plane
2
x
+
3
y
+
4
z
=
5
. Find the equation of the plane.

the plane passes through the point
A
(
1
,
2
,
3
)
A(1,2,3) and is parallel to the plane
2
x
+
3
y
+
4
z
=
5
2x+3y+4z=5, we can deduce the following:

Parallel planes have the same normal vector.
The normal vector to the given plane
2
x
+
3
y
+
4
z
=
5
2x+3y+4z=5 is
n
⃗
=
(
2
,
3
,
4
)
n
 =(2,3,4).
Equation of the plane:
The general equation of a plane is:
a
x
+
b
y
+
c
z
+
d
=
0
ax+by+cz+d=0
where
(
a
,
b
,
c
)
(a,b,c) is the normal vector to the plane.
Since the plane we are looking for is parallel to the plane
2
x
+
3
y
+
4
z
=
5
2x+3y+4z=5, it must have the same normal vector
(
2
,
3
,
4
)
(2,3,4). So, the equation of our plane will be of the form:

2
x
+
3
y
+
4
z
+
d
=
0
2x+3y+4z+d=0
where
d
d is a constant we need to find.

Substitute point
A
(
1
,
2
,
3
)
A(1,2,3) into the equation:
Since the plane passes through point
A
(
1
,
2
,
3
)
A(1,2,3), we substitute
x
=
1
x=1,
y
=
2
y=2, and
z
=
3
z=3 into the equation to find
d
d:
2
(
1
)
+
3
(
2
)
+
4
(
3
)
+
d
=
0
2(1)+3(2)+4(3)+d=0
Simplifying:
2
+
6
+
12
+
d
=
0
2+6+12+d=0
20
+
d
=
0
20+d=0
d
=
−
20
d=−20

Final Equation of the Plane:
The equation of the plane is:

2
x
+
3
y
+
4
z
−
20
=
0
2x+3y+4z−20=0
Or, equivalently:

2
x
+
3
y
+
4
z
=
20
2x+3y+4z=20

# Task 3
The plane passes through point
A
(
1
,
2
,
3
)
 and is perpendicular to the normal vector
n
=
[
2
,
3
,
4
]
. Find the equation of the plane.

a(x−x
0
​
 )+b(y−y
0
​
 )+c(z−z
0
​
 )=0
where
(
x
0
,
y
0
,
z
0
)
(x
0
​
 ,y
0
​
 ,z
0
​
 ) is a point on the plane and
(
a
,
b
,
c
)
(a,b,c) is the normal vector to the plane.

Given:

The plane passes through the point
A
(
1
,
2
,
3
)
A(1,2,3).
The normal vector to the plane is
n
⃗
=
(
2
,
3
,
4
)
n
 =(2,3,4).
Step 1: Use the point and the normal vector in the equation of the plane
Since the plane is perpendicular to the vector
n
⃗
=
(
2
,
3
,
4
)
n
 =(2,3,4), the coefficients of
x
x,
y
y, and
z
z in the plane equation will be
2
2,
3
3, and
4
4 respectively.

The equation of the plane is:

2
(
x
−
1
)
+
3
(
y
−
2
)
+
4
(
z
−
3
)
=
0
2(x−1)+3(y−2)+4(z−3)=0
Step 2: Expand the equation
Now expand the terms:

2
(
x
−
1
)
=
2
x
−
2
2(x−1)=2x−2
3
(
y
−
2
)
=
3
y
−
6
3(y−2)=3y−6
4
(
z
−
3
)
=
4
z
−
12
4(z−3)=4z−12
Substitute these into the equation:

2
x
−
2
+
3
y
−
6
+
4
z
−
12
=
0
2x−2+3y−6+4z−12=0
Simplify:

2
x
+
3
y
+
4
z
−
20
=
0
2x+3y+4z−20=0
Final Equation of the Plane:
2
x
+
3
y
+
4
z
=
20
2x+3y+4z=20
Final Answer:
The equation of the plane is:

2
x
+
3
y
+
4
z
=
20
2x+3y+4z=20
​

# Task 4
 We have two planes
2
x
+
3
y
+
4
z
=
5
 and
3
x
+
4
y
+
2
z
=
6
. Find the line of intersection of these planes.

To find the line of intersection of the two planes given by the equations:

2
x
+
3
y
+
4
z
=
5
2x+3y+4z=5
3
x
+
4
y
+
2
z
=
6
3x+4y+2z=6
we follow these steps:

Step 1: Express the system of equations
The system of equations is:

2
x
+
3
y
+
4
z
=
5
(Equation 1)
2x+3y+4z=5(Equation 1)
3
x
+
4
y
+
2
z
=
6
(Equation 2)
3x+4y+2z=6(Equation 2)
Step 2: Solve for one variable
We will eliminate one of the variables by manipulating the equations. First, let's eliminate
z
z.

Multiply Equation (1) by 2 and Equation (2) by 4 so that the coefficients of
z
z in both equations become equal:

2
(
2
x
+
3
y
+
4
z
)
=
2
(
5
)
⇒
4
x
+
6
y
+
8
z
=
10
(Equation 3)
2(2x+3y+4z)=2(5)⇒4x+6y+8z=10(Equation 3)
4
(
3
x
+
4
y
+
2
z
)
=
4
(
6
)
⇒
12
x
+
16
y
+
8
z
=
24
(Equation 4)
4(3x+4y+2z)=4(6)⇒12x+16y+8z=24(Equation 4)
Step 3: Subtract the two equations
Now, subtract Equation (3) from Equation (4) to eliminate
z
z:

(
12
x
+
16
y
+
8
z
)
−
(
4
x
+
6
y
+
8
z
)
=
24
−
10
(12x+16y+8z)−(4x+6y+8z)=24−10
Simplifying:

8
x
+
10
y
=
14
8x+10y=14
4
x
+
5
y
=
7
(Equation 5)
4x+5y=7(Equation 5)
Step 4: Express
y
y in terms of
x
x
From Equation (5), solve for
y
y in terms of
x
x:

y
=
7
−
4
x
5
(Equation 6)
y=
5
7−4x
​
 (Equation 6)
Step 5: Substitute
y
y into one of the original equations
Substitute Equation (6) into one of the original equations. Let's use Equation (1):

2
x
+
3
(
7
−
4
x
5
)
+
4
z
=
5
2x+3(
5
7−4x
​
 )+4z=5
Simplify:

2
x
+
3
(
7
−
4
x
)
5
+
4
z
=
5
2x+
5
3(7−4x)
​
 +4z=5
Multiply through by 5 to eliminate the denominator:

5
(
2
x
)
+
3
(
7
−
4
x
)
+
20
z
=
25
5(2x)+3(7−4x)+20z=25
10
x
+
21
−
12
x
+
20
z
=
25
10x+21−12x+20z=25
Simplifying further:

−
2
x
+
20
z
=
4
−2x+20z=4
x
−
10
z
=
−
2
(Equation 7)
x−10z=−2(Equation 7)
Step 6: Parametrize the solution
Solve Equation (7) for
x
x:

x
=
10
z
−
2
x=10z−2
Substitute this expression for
x
x into Equation (6) to find
y
y:

y
=
7
−
4
(
10
z
−
2
)
5
y=
5
7−4(10z−2)
​

Simplifying:

y
=
7
−
40
z
+
8
5
=
15
−
40
z
5
=
3
−
8
z
y=
5
7−40z+8
​
 =
5
15−40z
​
 =3−8z
Step 7: Parametrize the line of intersection
Now we have expressions for
x
x and
y
y in terms of
z
z:

x
=
10
z
−
2
x=10z−2
y
=
3
−
8
z
y=3−8z
We can express the parametric equations of the line of intersection as:

x
=
10
t
−
2
x=10t−2
y
=
3
−
8
t
y=3−8t
z
=
t
z=t
where
t
t is a parameter.

Final Answer:
The parametric equations of the line of intersection are:

x
=
10
t
−
2
,
y
=
3
−
8
t
,
z
=
t
x=10t−2,y=3−8t,z=t
​

# Task 5
Write the equation of the plane passing through point
A
(
1
,
2
,
3
)
 and parallel to vectors
v
1
→
=
[
1
,
0
,
1
]
 and
v
2
→
=
[
0
,
1
,
−
1
]
.

Find the normal vector of the plane
The plane is parallel to the vectors
v
⃗
1
v
  
1
​
  and
v
⃗
2
v
  
2
​
 . A vector normal to the plane,
n
⃗
n
 , is perpendicular to both
v
⃗
1
v
  
1
​
  and
v
⃗
2
v
  
2
​
 . We compute
n
⃗
n
  as the cross product of
v
⃗
1
v
  
1
​
  and
v
⃗
2
v
  
2
​
 :

n
⃗
=
v
⃗
1
×
v
⃗
2
n
 =
v
  
1
​
 ×
v
  
2
​

Using the determinant formula for the cross product:

n
⃗
=
∣
i
j
k
1
0
1
0
1
−
1

∣
n
 =
​
  
i
1
0
​
  
j
0
1
​
  
k
1
−1
​
  
​

Expand the determinant:

n
⃗
=
i
∣
0
1
1
−
1

∣
−
j
∣
1
1
0
−
1

∣
+
k
∣
1
0
0
1

∣
n
 =i
​
  
0
1
​
  
1
−1
​
  
​
 −j
​
  
1
0
​
  
1
−1
​
  
​
 +k
​
  
1
0
​
  
0
1
​
  
​

n
⃗
=
i
(
0
⋅
−
1
−
1
⋅
1
)
−
j
(
1
⋅
−
1
−
1
⋅
0
)
+
k
(
1
⋅
1
−
0
⋅
0
)
n
 =i(0⋅−1−1⋅1)−j(1⋅−1−1⋅0)+k(1⋅1−0⋅0)
n
⃗
=
i
(
−
1
)
−
j
(
−
1
)
+
k
(
1
)
n
 =i(−1)−j(−1)+k(1)
n
⃗
=
−
i
+
j
+
k
n
 =−i+j+k
Thus:

n
⃗
=
[
−
1
,
1
,
1
]
n
 =[−1,1,1]
Step 2: Write the equation of the plane
The general equation of a plane is:

n
1
(
x
−
x
0
)
+
n
2
(
y
−
y
0
)
+
n
3
(
z
−
z
0
)
=
0
n
1
​
 (x−x
0
​
 )+n
2
​
 (y−y
0
​
 )+n
3
​
 (z−z
0
​
 )=0
Here:

n
⃗
=
[
−
1
,
1
,
1
]
n
 =[−1,1,1], so
n
1
=
−
1
n
1
​
 =−1,
n
2
=
1
n
2
​
 =1,
n
3
=
1
n
3
​
 =1,
The point
A
(
1
,
2
,
3
)
A(1,2,3) gives
x
0
=
1
x
0
​
 =1,
y
0
=
2
y
0
​
 =2,
z
0
=
3
z
0
​
 =3.
Substitute into the equation:

−
1
(
x
−
1
)
+
1
(
y
−
2
)
+
1
(
z
−
3
)
=
0
−1(x−1)+1(y−2)+1(z−3)=0
Simplify:

−
x
+
1
+
y
−
2
+
z
−
3
=
0
−x+1+y−2+z−3=0
−
x
+
y
+
z
−
4
=
0
−x+y+z−4=0
Final Answer:
The equation of the plane is:

−
x
+
y
+
z
=
4
−x+y+z=4
​

# Task 6
 We have the plane
2
x
+
3
y
+
4
z
=
5
. Find an example of a plane parallel and perpendicular to it.

Plane Parallel to
2
x
+
3
y
+
4
z
=
5
2x+3y+4z=5
A plane parallel to the given plane must have the same normal vector
n
⃗
=
[
2
,
3
,
4
]
n
 =[2,3,4]. The general equation of a plane parallel to the given one is:

2
x
+
3
y
+
4
z
=
d
2x+3y+4z=d
Here,
d
d can be any constant different from
5
5. For example, let
d
=
10
d=10. The equation of a parallel plane is:

2
x
+
3
y
+
4
z
=
10
2x+3y+4z=10
2. Plane Perpendicular to
2
x
+
3
y
+
4
z
=
5
2x+3y+4z=5
A plane perpendicular to the given plane must have a normal vector perpendicular to
n
⃗
=
[
2
,
3
,
4
]
n
 =[2,3,4]. Let the normal vector of the perpendicular plane be
m
⃗
=
[
a
,
b
,
c
]
m
 =[a,b,c]. For the planes to be perpendicular, the dot product of their normal vectors must be zero:

n
⃗
⋅
m
⃗
=
0
n
 ⋅
m
 =0
2
a
+
3
b
+
4
c
=
0
2a+3b+4c=0
We can choose any
a
a,
b
b, and
c
c satisfying this equation. For simplicity, let
a
=
1
a=1 and
b
=
−
1
b=−1. Substitute these into the equation to solve for
c
c:

2
(
1
)
+
3
(
−
1
)
+
4
c
=
0
2(1)+3(−1)+4c=0
2
−
3
+
4
c
=
0
2−3+4c=0
−
1
+
4
c
=
0
−1+4c=0
c
=
1
4
c=
4
1
​

Thus, the normal vector of the perpendicular plane is
m
⃗
=
[
1
,
−
1
,
1
4
]
m
 =[1,−1,
4
1
​
 ]. The equation of the perpendicular plane passing through the origin (for simplicity) is:

1
x
−
1
y
+
1
4
z
=
0
1x−1y+
4
1
​
 z=0
Multiply through by 4 to clear the fraction:

4
x
−
4
y
+
z
=
0
4x−4y+z=0
Final Answer:
Example of a parallel plane:
2
x
+
3
y
+
4
z
=
10
2x+3y+4z=10
Example of a perpendicular plane:
4
x
−
4
y
+
z
=
0
4x−4y+z=0

# Task 7
We have the plane
2
x
+
3
y
+
4
z
=
5
 and point
A
(
1
,
2
,
3
)
. Find the distance from point
A
 to this plane.

Identify values
From the plane equation
2
x
+
3
y
+
4
z
=
5
2x+3y+4z=5:

A
=
2
A=2,
B
=
3
B=3,
C
=
4
C=4, and
D
=
5
D=5.
From the point
A
(
1
,
2
,
3
)
A(1,2,3):

x
1
=
1
x
1
​
 =1,
y
1
=
2
y
1
​
 =2,
z
1
=
3
z
1
​
 =3.
Step 2: Substitute into the formula
d
=
∣
2
(
1
)
+
3
(
2
)
+
4
(
3
)
−
5
∣
2
2
+
3
2
+
4
2
d=
2
2
 +3
2
 +4
2

​

∣2(1)+3(2)+4(3)−5∣
​

Simplify the numerator:

2
(
1
)
+
3
(
2
)
+
4
(
3
)
−
5
=
2
+
6
+
12
−
5
=
15
2(1)+3(2)+4(3)−5=2+6+12−5=15
Simplify the denominator:

2
2
+
3
2
+
4
2
=
4
+
9
+
16
=
29
2
2
 +3
2
 +4
2

​
 =
4+9+16
​
 =
29
​

Step 3: Compute the distance
d
=
∣
15
∣
29
=
15
29
d=
29
​

∣15∣
​
 =
29
​

15
​

For a rationalized denominator:

d
=
15
29
29
d=
29
15
29
​

​

Final Answer:
The distance from point
A
(
1
,
2
,
3
)
A(1,2,3) to the plane
2
x
+
3
y
+
4
z
=
5
2x+3y+4z=5 is:

15
29
29
29
15
29
​

​

​

# Task 8
The plane intersects the coordinate axes at points
A
(
2
,
0
,
0
)
,
B
(
0
,
3
,
0
)
, and
C
(
0
,
0
,
4
)
. Find the equation of the plane.

Substitute the intercepts
The equation of the plane becomes:

x
2
+
y
3
+
z
4
=
1
2
x
​
 +
3
y
​
 +
4
z
​
 =1
Step 2: Clear the fractions
Multiply through by the least common multiple (LCM) of 2, 3, and 4, which is 12:

12
⋅
x
2
+
12
⋅
y
3
+
12
⋅
z
4
=
12
12⋅
2
x
​
 +12⋅
3
y
​
 +12⋅
4
z
​
 =12
Simplify:

6
x
+
4
y
+
3
z
=
12
6x+4y+3z=12
Final Answer:
The equation of the plane is:

6
x
+
4
y
+
3
z
=
12
6x+4y+3z=12
​

# Task 9
Calculate the angle between the plane
x
+
y
+
z
=
1
 and the plane
x
=
0
 (i.e., the
y
z
plane).

Extract the normal vectors
The angle between two planes is determined by the angle between their normal vectors.

For the plane
x
+
y
+
z
=
1
x+y+z=1, the normal vector is:
n
⃗
1
=
[
1
,
1
,
1
]
n
  
1
​
 =[1,1,1]
For the plane
x
=
0
x=0 (the
y
z
yz-plane), the normal vector is:
n
⃗
2
=
[
1
,
0
,
0
]
n
  
2
​
 =[1,0,0]
Step 2: Use the formula for the angle between two vectors
The angle
θ
θ between two vectors
n
⃗
1
n
  
1
​
  and
n
⃗
2
n
  
2
​
  is given by:

cos
⁡
θ
=
∣
n
⃗
1
⋅
n
⃗
2
∣
∥
n
⃗
1
∥
∥
n
⃗
2
∥
cosθ=
∥
n
  
1
​
 ∥∥
n
  
2
​
 ∥
∣
n
  
1
​
 ⋅
n
  
2
​
 ∣
​

Step 3: Compute the dot product
The dot product
n
⃗
1
⋅
n
⃗
2
n
  
1
​
 ⋅
n
  
2
​
  is:

n
⃗
1
⋅
n
⃗
2
=
(
1
)
(
1
)
+
(
1
)
(
0
)
+
(
1
)
(
0
)
=
1
n
  
1
​
 ⋅
n
  
2
​
 =(1)(1)+(1)(0)+(1)(0)=1
Step 4: Compute the magnitudes
The magnitude of
n
⃗
1
n
  
1
​
  is:

∥
n
⃗
1
∥
=
1
2
+
1
2
+
1
2
=
3
∥
n
  
1
​
 ∥=
1
2
 +1
2
 +1
2

​
 =
3
​

The magnitude of
n
⃗
2
n
  
2
​
  is:

∥
n
⃗
2
∥
=
1
2
+
0
2
+
0
2
=
1
∥
n
  
2
​
 ∥=
1
2
 +0
2
 +0
2

​
 =1
Step 5: Compute
cos
⁡
θ
cosθ
Substitute into the formula:

cos
⁡
θ
=
∣
n
⃗
1
⋅
n
⃗
2
∣
∥
n
⃗
1
∥
∥
n
⃗
2
∥
cosθ=
∥
n
  
1
​
 ∥∥
n
  
2
​
 ∥
∣
n
  
1
​
 ⋅
n
  
2
​
 ∣
​

cos
⁡
θ
=
∣
1
∣
3
⋅
1
=
1
3
cosθ=
3
​
 ⋅1
∣1∣
​
 =
3
​

1
​

Step 6: Compute
θ
θ
Take the inverse cosine to find
θ
θ:

θ
=
cos
⁡
−
1
(
1
3
)
θ=cos
−1
 (
3
​

1
​
 )
In degrees:

θ
≈
54.7
4
∘
θ≈54.74
∘

Final Answer:
The angle between the planes
x
+
y
+
z
=
1
x+y+z=1 and
x
=
0
x=0 (the
y
z
yz-plane) is:

cos
⁡
−
1
(
1
3
)
 or approximately
54.7
4
∘
cos
−1
 (
3
​

1
​
 ) or approximately 54.74
∘

​

# Task 10
Find the vector perpendicular to the plane
x
+
y
+
z
=
1
.

Extract the normal vector
The coefficients of
x
x,
y
y, and
z
z are
1
1,
1
1, and
1
1, respectively. Thus, the normal vector is:

n
⃗
=
[
1
,
1
,
1
]
n
 =[1,1,1]
Final Answer:
The vector perpendicular to the plane
x
+
y
+
z
=
1
x+y+z=1 is:

n
⃗
=
[
1
,
1
,
1
]
n
 =[1,1,1]
​
"""